# Generated by Django 4.1.4 on 2022-12-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmodel',
            name='cpassword',
        ),
    ]
