# Generated by Django 4.1.4 on 2023-01-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_regmodel_address_alter_regmodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=35)),
                ('jtype', models.CharField(choices=[('parttime', 'part-time'), ('Full-time', 'Full-time')], max_length=50)),
                ('worktype', models.CharField(choices=[('hybrid', 'hybrid'), ('remote', 'remote')], max_length=30)),
                ('exp', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20)),
                ('qua', models.CharField(max_length=100)),
            ],
        ),
    ]
