# Generated by Django 4.1.4 on 2023-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_addmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmodel',
            name='jtype',
            field=models.CharField(choices=[('parttime', 'parttime'), ('Full-time', 'Full-time')], max_length=50),
        ),
    ]
