# Generated by Django 4.1.4 on 2023-01-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_addmodel_jtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmodel',
            name='jtype',
            field=models.CharField(choices=[('select', 'select'), ('parttime', 'parttime'), ('Full-time', 'Full-time')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addmodel',
            name='worktype',
            field=models.CharField(choices=[('select', 'select'), ('hybrid', 'hybrid'), ('remote', 'remote')], max_length=100),
        ),
    ]
