# Generated by Django 4.1.4 on 2023-01-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_alter_addmodel_jtype_alter_addmodel_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmodel',
            name='jtype',
            field=models.CharField(choices=[('parttime', 'parttime'), ('Full-time', 'Full-time')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addmodel',
            name='worktype',
            field=models.CharField(choices=[('hybrid', 'hybrid'), ('remote', 'remote')], max_length=100),
        ),
    ]
