# Generated by Django 4.1.4 on 2023-01-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_addmodel_jtype_alter_addmodel_worktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='addprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jobapp/static')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='')),
                ('eduqua', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
