# Generated by Django 4.1.4 on 2023-01-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_addprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprofile',
            name='resume',
            field=models.FileField(upload_to='jobapp/static'),
        ),
    ]
