# Generated by Django 4.1.3 on 2022-11-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.FileField(upload_to='sample_app/static')),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
